## Compute sample-wise error metrics

### Setup and Helper Functions

#### Imports

In [1]:
import pandas as pd
from pathlib import Path
from pepbench.evaluation._error_metrics import error, abs_error, rel_error, abs_rel_error
from b_point_ml_experiments.data_handling import describe_ml_results_df
from b_point_ml_experiments.export import create_ml_algo_performance_table

#### Datapaths

In [ ]:
data_path = Path("../../results")

### Load data

In [4]:
merged_ml_results = pd.read_csv(data_path.joinpath("merged_ml_results_b_point_paper_rr_only.csv"), index_col=[0,1,2,3])
merged_ml_results

                                                            b_point_sample_reference  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          388.0
                                    1                                          404.0
                                    3                                          376.0
                                    4                                          390.0
                                    5                                          386.0
...                                                                              ...
VP_032      tsst      Talk          39                                         310.0
                                    40                                         322.0
                                    41                                         340.0
                                    42                                         311.0
                                    43                                         307.0

                                                            arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 438.0
                                    1                                                 340.0
                                    3                                                 382.0
                                    4                                                 394.0
                                    5                                                 398.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                335.0
                                    40                                                331.0
                                    41                                                317.0
                                    42                                                365.0
                                    43                                                342.0

                                                            arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                             398.0
                                    1                                             350.0
                                    3                                             296.0
                                    4                                             344.0
                                    5                                             312.0
...                                                                                 ...
VP_032      tsst      Talk          39                                            276.0
                                    40                                            298.0
                                    41                                            300.0
                                    42                                            324.0
                                    43                                            313.0

                                                            arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                            394.0
                                    1                                            244.0
                                    3                                            386.0
                                    4                                            396.0
                                    5                                            388.0
...                                                                                ...
VP_032      tsst      Talk          39                                           324.0
                                    40                                           330.0
                                    41                                           348.0
                                    42                                           366.0
                                    43                                           356.0

                                                            debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              452.0
                                    1                                              388.0
                                    3                                              366.0
                                    4                                              376.0
                                    5                                              418.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             300.0
                                    40                                             311.0
                                    41                                             330.0
                                    42                                             347.0
                                    43                                             285.0

                                                            drost2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           400.0
                                    1                           420.0
                                    3                           386.0
                                    4                           396.0
                                    5                           392.0
...                                                               ...
VP_032      tsst      Talk          39                          318.0
                                    40                          322.0
                                    41                          343.0
                                    42                          354.0
                                    43                          332.0

                                                            forouzanfar2018  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                 550.0
                                    1                                 402.0
                                    3                                 388.0
                                    4                                 398.0
                                    5                                 390.0
...                                                                     ...
VP_032      tsst      Talk          39                                306.0
                                    40                                311.0
                                    41                                309.0
                                    42                                305.0
                                    43                                302.0

                                                            lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              412.0
                                    1                                              404.0
                                    3                                              366.0
                                    4                                              372.0
                                    5                                              378.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             305.0
                                    40                                             321.0
                                    41                                             332.0
                                    42                                             351.0
                                    43                                             341.0

                                                            lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 384.0
                                    1                                                 384.0
                                    3                                                 348.0
                                    4                                                 348.0
                                    5                                                 354.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                294.0
                                    40                                                303.0
                                    41                                                322.0
                                    42                                                337.0
                                    43                                                329.0

                                                            miljkovic2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                               442.0
                                    1                               288.0
                                    3                               386.0
                                    4                               398.0
                                    5                               392.0
...                                                                   ...
VP_032      tsst      Talk          39                              308.0
                                    40                              329.0
                                    41                              292.0
                                    42                              312.0
                                    43                              334.0

                                                            ...  \
participant condition phase         heartbeat_id_reference  ...
GDN0005     Dummy     HoldingBreath 0                       ...
                                    1                       ...
                                    3                       ...
                                    4                       ...
                                    5                       ...
...                                                         ...
VP_032      tsst      Talk          39                      ...
                                    40                      ...
                                    41                      ...
                                    42                      ...
                                    43                      ...

                                                            SS_KBest_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    412.398584
                                    1                                                    403.408903
                                    3                                                    376.768489
                                    4                                                    388.625256
                                    5                                                    385.761830
...                                                                                             ...
VP_032      tsst      Talk          39                                                   309.424969
                                    40                                                   312.280534
                                    41                                                   331.079043
                                    42                                                   342.187956
                                    43                                                   307.324979

                                                            SS_KBest_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    421.288455
                                    1                                                    401.485786
                                    3                                                    376.403625
                                    4                                                    388.643213
                                    5                                                    386.743597
...                                                                                             ...
VP_032      tsst      Talk          39                                                   319.918637
                                    40                                                   317.460122
                                    41                                                   329.227094
                                    42                                                   339.654610
                                    43                                                   314.443751

                                                            MinMax_SFM_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                           392.0
                                    1                                                           406.0
                                    3                                                           376.0
                                    4                                                           388.0
                                    5                                                           384.0
...                                                                                               ...
VP_032      tsst      Talk          39                                                          311.0
                                    40                                                          321.0
                                    41                                                          334.0
                                    42                                                          351.5
                                    43                                                          307.5

                                                            MinMax_SFM_RFR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      430.592322
                                    1                                                      404.075637
                                    3                                                      375.332204
                                    4                                                      389.011683
                                    5                                                      385.868359
...                                                                                               ...
VP_032      tsst      Talk          39                                                     310.134872
                                    40                                                     317.331053
                                    41                                                     330.211990
                                    42                                                     335.669733
                                    43                                                     310.617416

                                                            MinMax_SFM_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      415.841272
                                    1                                                      405.752970
                                    3                                                      377.956802
                                    4                                                      388.530034
                                    5                                                      386.934831
...                                                                                               ...
VP_032      tsst      Talk          39                                                     308.018902
                                    40                                                     310.554869
                                    41                                                     330.103150
                                    42                                                     339.014104
                                    43                                                     313.036780

                                                            MinMax_SFM_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      416.688480
                                    1                                                      396.160236
                                    3                                                      377.268411
                                    4                                                      387.233813
                                    5                                                      390.040129
...                                                                                               ...
VP_032      tsst      Talk          39                                                     310.277235
                                    40                                                     315.145165
                                    41                                                     329.741920
                                    42                                                     342.487887
                                    43                                                     306.995532

                                                            MinMax_KBest_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                             403.0
                                    1                                                             404.0
                                    3                                                             376.0
                                    4                                                             388.0
                                    5                                                             386.0

### Compute error metrics and build combined dataframe

In [ ]:
ref_data = merged_ml_results['b_point_sample_reference']
iterable = merged_ml_results.drop(columns=['b_point_sample_reference', 'rr_interval_ms_estimated'])
merged_ml_results_metrics = pd.DataFrame(index=merged_ml_results.index)
new_columns_list = []
for column in iterable.columns:
    new_columns_list.append(error(ref_data=ref_data, est_data=iterable[column]).rename(f"{column}_error"))
    new_columns_list.append(rel_error(ref_data=ref_data, est_data=iterable[column]).rename(f"{column}_rel_error"))
    new_columns_list.append(abs_error(ref_data=ref_data, est_data=iterable[column]).rename(f"{column}_abs_error"))
    new_columns_list.append(abs_rel_error(ref_data=ref_data, est_data=iterable[column]).rename(f"{column}_abs_rel_error"))

merged_ml_results_metrics = pd.concat(new_columns_list, axis=1)
merged_ml_results_metrics

### Save the dataframe containing the error metrices

In [7]:
# merged_ml_results_metrics.to_csv(data_path.joinpath("merged_ml_results_b_point_error_metrics_rr_only.csv"))

### Format dataframe

In [8]:
summarized_error_metrics = describe_ml_results_df(merged_ml_results_metrics)
summarized_error_metrics

                                                       mean             \
metric_type                                             MAE       MARE
B-Point Algorithm
MinMax_None_RFR_RR-Interval-Include-Nan            8.127195   2.457700
SS_None_RFR_RR-Interval-Include-Nan                8.176128   2.470750
MinMax_None_RFR_Without-RR-Interval-Include-Nan    8.260385   2.516612
SS_SFM_RFR_RR-Interval-Median-Imputed              8.303370   2.510506
SS_None_RFR_Without-RR-Interval-Include-Nan        8.316623   2.538004
MinMax_KBest_RFR_RR-Interval-Median-Imputed        8.332127   2.525267
MinMax_SFM_RFR_RR-Interval-Median-Imputed          8.404488   2.552079
SS_KBest_RFR_RR-Interval-Median-Imputed            8.417848   2.551505
SS_KBest_SVR_RR-Interval-Median-Imputed            8.471520   2.590958
MinMax_SFM_DTR_RR-Interval-Median-Imputed          8.625426   2.634158
MinMax_KBest_DTR_RR-Interval-Median-Imputed        8.790088   2.673068
SS_SFM_DTR_RR-Interval-Median-Imputed              8.792737   2.685400
SS_SFM_SVR_RR-Interval-Median-Imputed              8.801365   2.640702
SS_KBest_DTR_RR-Interval-Median-Imputed            8.998698   2.710869
MinMax_KBest_KNR_RR-Interval-Median-Imputed        9.385823   2.864359
SS_KBest_KNR_RR-Interval-Median-Imputed            9.417666   2.868307
MinMax_SFM_SVR_RR-Interval-Median-Imputed          9.453493   2.833092
MinMax_KBest_SVR_RR-Interval-Median-Imputed        9.457950   2.841555
SS_SFM_KNR_RR-Interval-Median-Imputed              9.526608   2.845926
MinMax_SFM_KNR_RR-Interval-Median-Imputed          9.631261   2.873993
MinMax_None_DTR_RR-Interval-Include-Nan           10.064355   3.017120
SS_None_DTR_RR-Interval-Include-Nan               10.175344   3.054235
SS_None_DTR_Without-RR-Interval-Include-Nan       10.229854   3.115319
MinMax_None_DTR_Without-RR-Interval-Include-Nan   10.341293   3.142197
drost2022                                         17.926862   5.343727
lozano2007-linear-regression                      19.621141   6.336696
debski1993-second-derivative                      20.467776   5.962337
forouzanfar2018                                   24.396659   7.480865
miljkovic2022                                     24.932912   7.479379
lozano2007-quadratic-regression                   25.766260   7.722660
sherwood1990                                      29.191814   8.409976
arbol2017-isoelectric-crossings                   30.788043   9.049629
stern1985                                         30.930807   9.673564
arbol2017-second-derivative                       44.625145  13.537015
arbol2017-third-derivative                        44.784551  13.297414
pale2021                                         105.452086  29.408996

                                                                       \
metric_type                                             ME        MRE
B-Point Algorithm
MinMax_None_RFR_RR-Interval-Include-Nan          -0.034290  -0.221008
SS_None_RFR_RR-Interval-Include-Nan              -0.016219  -0.219021
MinMax_None_RFR_Without-RR-Interval-Include-Nan  -0.102849  -0.277577
SS_SFM_RFR_RR-Interval-Median-Imputed            -0.032807  -0.232501
SS_None_RFR_Without-RR-Interval-Include-Nan      -0.122022  -0.290668
MinMax_KBest_RFR_RR-Interval-Median-Imputed       0.000975  -0.215482
MinMax_SFM_RFR_RR-Interval-Median-Imputed        -0.058733  -0.238909
SS_KBest_RFR_RR-Interval-Median-Imputed          -0.061609  -0.240501
SS_KBest_SVR_RR-Interval-Median-Imputed          -0.197264  -0.296733
MinMax_SFM_DTR_RR-Interval-Median-Imputed        -0.085204  -0.205887
MinMax_KBest_DTR_RR-Interval-Median-Imputed       0.076854  -0.126659
SS_SFM_DTR_RR-Interval-Median-Imputed            -0.266610  -0.248855
SS_SFM_SVR_RR-Interval-Median-Imputed            -0.150851  -0.205760
SS_KBest_DTR_RR-Interval-Median-Imputed           0.203582  -0.105811
MinMax_KBest_KNR_RR-Interval-Median-Imputed       0.076712  -0.256916
SS_KBest_KNR_RR-Interval-Median-Imputed           0.167532  -0.232313
MinMax_SFM_SVR_RR-Interval-Median-Imputed        -0.192886  -0.185997
MinMax_KBest_SVR_RR-Interval-Median-Imputed      -0.420695  -0.296452
SS_SFM_KNR_RR-Interval-Median-Imputed             0.130127  -0.208670
MinMax_SFM_KNR_RR-Interval-Median-Imputed         0.078602  -0.222913
MinMax_None_DTR_RR-Interval-Include-Nan           0.056381  -0.209605
SS_None_DTR_RR-Interval-Include-Nan              -0.129379  -0.258991
SS_None_DTR_Without-RR-Interval-Include-Nan      -0.073907  -0.311698
MinMax_None_DTR_Without-RR-Interval-Include-Nan  -0.385196  -0.395677
drost2022                                       -11.288371  -3.195510
lozano2007-linear-regression                    -10.772133  -4.137510
debski1993-second-derivative                     -3.033287  -0.531796
forouzanfar2018                                  18.824831   6.101112
miljkovic2022                                     7.315508   1.842702
lozano2007-quadratic-regression                   4.957292  -0.281833
sherwood1990                                     -2.490822  -1.593685
arbol2017-isoelectric-crossings                   0.041073  -0.660046
stern1985                                        28.585912   9.003108
arbol2017-second-derivative                      40.632441  12.365742
arbol2017-third-derivative                       11.243748   2.904541
pale2021                                         71.901059  18.897111

                                                        std             \
metric_type                                             MAE       MARE
B-Point Algorithm
MinMax_None_RFR_RR-Interval-Include-Nan           12.119868   3.924358
SS_None_RFR_RR-Interval-Include-Nan               12.190455   3.948903
MinMax_None_RFR_Without-RR-Interval-Include-Nan   13.029197   4.453063
SS_SFM_RFR_RR-Interval-Median-Imputed             12.295232   3.921546
SS_None_RFR_Without-RR-Interval-Include-Nan       13.044290   4.462719
MinMax_KBest_RFR_RR-Interval-Median-Imputed       12.295956   3.932469
MinMax_SFM_RFR_RR-Interval-Median-Imputed         12.364311   3.967338
SS_KBest_RFR_RR-Interval-Median-Imputed           12.597694   3.991527
SS_KBest_SVR_RR-Interval-Median-Imputed           15.932213   5.420518
MinMax_SFM_DTR_RR-Interval-Median-Imputed         14.691449   4.597049
MinMax_KBest_DTR_RR-Interval-Median-Imputed       15.779622   4.787593
SS_SFM_DTR_RR-Interval-Median-Imputed             14.672813   4.644806
SS_SFM_SVR_RR-Interval-Median-Imputed             13.303904   4.100891
SS_KBest_DTR_RR-Interval-Median-Imputed           15.521428   4.699524
MinMax_KBest_KNR_RR-Interval-Median-Imputed       14.907037   4.981645
SS_KBest_KNR_RR-Interval-Median-Imputed           14.835349   4.951133
MinMax_SFM_SVR_RR-Interval-Median-Imputed         14.473916   4.439427
MinMax_KBest_SVR_RR-Interval-Median-Imputed       14.604804   4.569453
SS_SFM_KNR_RR-Interval-Median-Imputed             13.161813   4.164662
MinMax_SFM_KNR_RR-Interval-Median-Imputed         13.043401   4.141778
MinMax_None_DTR_RR-Interval-Include-Nan           13.719551   4.373386
SS_None_DTR_RR-Interval-Include-Nan               14.347751   4.674280
SS_None_DTR_Without-RR-Interval-Include-Nan       15.513879   5.383830
MinMax_None_DTR_Without-RR-Interval-Include-Nan   15.318446   5.305604
drost2022                                         23.016958   7.675758
lozano2007-linear-regression                      17.461041   6.474221
debski1993-second-derivative                      21.369166   6.468776
forouzanfar2018                                   35.280704  11.310439
miljkovic2022                                     35.193118  11.652942
lozano2007-quadratic-regression                   25.877538   8.163458
sherwood1990                                      20.050856   5.665629
arbol2017-isoelectric-crossings                   26.471224   8.143995
stern1985                                         41.691169  13.764898
arbol2017-second-derivative                       28.701568  10.114033
arbol2017-third-derivative                        55.223422  18.714293
pale2021                                         113.312657  29.323507


metric_type                                              ME        MRE
B-Point Algorithm
MinMax_None_RFR_RR-Interval-Include-Nan           14.592711   4.625209
SS_None_RFR_RR-Interval-Include-Nan               14.678622   4.653065
MinMax_None_RFR_Without-RR-Interval-Include-Nan   15.426906   5.107506
SS_SFM_RFR_RR-Interval-Median-Imputed             14.836569   4.650555
SS_None_RFR_Without-RR-Interval-Include-Nan       15.469680   5.125759
MinMax_KBest_RFR_RR-Interval-Median-Imputed       14.853320   4.668556
MinMax_SFM_RFR_RR-Interval-Median-Imputed         14.950401   4.711304
SS_KBest_RFR_RR-Interval-Median-Imputed           15.151390   4.731301
SS_KBest_SVR_RR-Interval-Median-Imputed           18.043547   6.000636
MinMax_SFM_DTR_RR-Interval-Median-Imputed         17.036316   5.294325
MinMax_KBest_DTR_RR-Interval-Median-Imputed       18.062756   5.481874
SS_SFM_DTR_RR-Interval-Median-Imputed             17.103786   5.359506
SS_SFM_SVR_RR-Interval-Median-Imputed             15.951240   4.873284
SS_KBest_DTR_RR-Interval-Median-Imputed           17.940377   5.424371
MinMax_KBest_KNR_RR-Interval-Median-Imputed       17.615773   5.740738
SS_KBest_KNR_RR-Interval-Median-Imputed           17.571565   5.717313
MinMax_SFM_SVR_RR-Interval-Median-Imputed         17.286804   5.263178
MinMax_KBest_SVR_RR-Interval-Median-Imputed       17.394947   5.372818
SS_SFM_KNR_RR-Interval-Median-Imputed             16.247486   5.039929
MinMax_SFM_KNR_RR-Interval-Median-Imputed         16.213996   5.036389
MinMax_None_DTR_RR-Interval-Include-Nan           17.015380   5.309085
SS_None_DTR_RR-Interval-Include-Nan               17.589431   5.577723
SS_None_DTR_Without-RR-Interval-Include-Nan       18.583170   6.212450
MinMax_None_DTR_Without-RR-Interval-Include-Nan   18.478589   6.153628
drost2022                                         26.902466   8.789939
lozano2007-linear-regression                      23.955421   8.059300
debski1993-second-derivative                      29.434812   8.781513
forouzanfar2018                                   38.543126  12.110636
miljkovic2022                                     42.505759  13.723749
lozano2007-quadratic-regression                   36.180510  11.234207
sherwood1990                                      35.328066  10.014663
arbol2017-isoelectric-crossings                   40.604336  12.156975
stern1985                                         43.332742  14.212509
arbol2017-second-derivative                       34.120648  11.516752
arbol2017-third-derivative                        70.207035  22.773332
pale2021                                         137.079057  36.982448

In [10]:
# summarized_error_metrics.to_csv(data_path.joinpath("summarized_b_point_error_metrics_rr_only.csv"))

In [14]:
metric_export_paper = create_ml_algo_performance_table(summarized_error_metrics, n_algos=40)
metric_export_paper

,MAE,MARE,ME,MRE
B-Point Algorithm,,,,
MinMax_None_RFR_RR-Interval-Include-Nan,8.13 ± 12.12,2.46 ± 3.92,-0.03 ± 14.59,-0.22 ± 4.63
SS_None_RFR_RR-Interval-Include-Nan,8.18 ± 12.19,2.47 ± 3.95,-0.02 ± 14.68,-0.22 ± 4.65
MinMax_None_RFR_Without-RR-Interval-Include-Nan,8.26 ± 13.03,2.52 ± 4.45,-0.1 ± 15.43,-0.28 ± 5.11
SS_SFM_RFR_RR-Interval-Median-Imputed,8.3 ± 12.3,2.51 ± 3.92,-0.03 ± 14.84,-0.23 ± 4.65
SS_None_RFR_Without-RR-Interval-Include-Nan,8.32 ± 13.04,2.54 ± 4.46,-0.12 ± 15.47,-0.29 ± 5.13
MinMax_KBest_RFR_RR-Interval-Median-Imputed,8.33 ± 12.3,2.53 ± 3.93,0.0 ± 14.85,-0.22 ± 4.67
MinMax_SFM_RFR_RR-Interval-Median-Imputed,8.4 ± 12.36,2.55 ± 3.97,-0.06 ± 14.95,-0.24 ± 4.71
SS_KBest_RFR_RR-Interval-Median-Imputed,8.42 ± 12.6,2.55 ± 3.99,-0.06 ± 15.15,-0.24 ± 4.73
SS_KBest_SVR_RR-Interval-Median-Imputed,8.47 ± 15.93,2.59 ± 5.42,-0.2 ± 18.04,-0.3 ± 6.0
MinMax_SFM_DTR_RR-Interval-Median-Imputed,8.63 ± 14.69,2.63 ± 4.6,-0.09 ± 17.04,-0.21 ± 5.29
MinMax_KBest_DTR_RR-Interval-Median-Imputed,8.79 ± 15.78,2.67 ± 4.79,0.08 ± 18.06,-0.13 ± 5.48
SS_SFM_DTR_RR-Interval-Median-Imputed,8.79 ± 14.67,2.69 ± 4.64,-0.27 ± 17.1,-0.25 ± 5.36
SS_SFM_SVR_RR-Interval-Median-Imputed,8.8 ± 13.3,2.64 ± 4.1,-0.15 ± 15.95,-0.21 ± 4.87
SS_KBest_DTR_RR-Interval-Median-Imputed,9.0 ± 15.52,2.71 ± 4.7,0.2 ± 17.94,-0.11 ± 5.42
MinMax_KBest_KNR_RR-Interval-Median-Imputed,9.39 ± 14.91,2.86 ± 4.98,0.08 ± 17.62,-0.26 ± 5.74
SS_KBest_KNR_RR-Interval-Median-Imputed,9.42 ± 14.84,2.87 ± 4.95,0.17 ± 17.57,-0.23 ± 5.72
MinMax_SFM_SVR_RR-Interval-Median-Imputed,9.45 ± 14.47,2.83 ± 4.44,-0.19 ± 17.29,-0.19 ± 5.26
MinMax_KBest_SVR_RR-Interval-Median-Imputed,9.46 ± 14.6,2.84 ± 4.57,-0.42 ± 17.39,-0.3 ± 5.37
SS_SFM_KNR_RR-Interval-Median-Imputed,9.53 ± 13.16,2.85 ± 4.16,0.13 ± 16.25,-0.21 ± 5.04
MinMax_SFM_KNR_RR-Interval-Median-Imputed,9.63 ± 13.04,2.87 ± 4.14,0.08 ± 16.21,-0.22 ± 5.04
MinMax_None_DTR_RR-Interval-Include-Nan,10.06 ± 13.72,3.02 ± 4.37,0.06 ± 17.02,-0.21 ± 5.31
SS_None_DTR_RR-Interval-Include-Nan,10.18 ± 14.35,3.05 ± 4.67,-0.13 ± 17.59,-0.26 ± 5.58
SS_None_DTR_Without-RR-Interval-Include-Nan,10.23 ± 15.51,3.12 ± 5.38,-0.07 ± 18.58,-0.31 ± 6.21
MinMax_None_DTR_Without-RR-Interval-Include-Nan,10.34 ± 15.32,3.14 ± 5.31,-0.39 ± 18.48,-0.4 ± 6.15
drost2022,17.93 ± 23.02,5.34 ± 7.68,-11.29 ± 26.9,-3.2 ± 8.79
lozano2007-linear-regression,19.62 ± 17.46,6.34 ± 6.47,-10.77 ± 23.96,-4.14 ± 8.06
debski1993-second-derivative,20.47 ± 21.37,5.96 ± 6.47,-3.03 ± 29.43,-0.53 ± 8.78
forouzanfar2018,24.4 ± 35.28,7.48 ± 11.31,18.82 ± 38.54,6.1 ± 12.11
miljkovic2022,24.93 ± 35.19,7.48 ± 11.65,7.32 ± 42.51,1.84 ± 13.72
lozano2007-quadratic-regression,25.77 ± 25.88,7.72 ± 8.16,4.96 ± 36.18,-0.28 ± 11.23
sherwood1990,29.19 ± 20.05,8.41 ± 5.67,-2.49 ± 35.33,-1.59 ± 10.01
arbol2017-isoelectric-crossings,30.79 ± 26.47,9.05 ± 8.14,0.04 ± 40.6,-0.66 ± 12.16
stern1985,30.93 ± 41.69,9.67 ± 13.76,28.59 ± 43.33,9.0 ± 14.21
arbol2017-second-derivative,44.63 ± 28.7,13.54 ± 10.11,40.63 ± 34.12,12.37 ± 11.52
arbol2017-third-derivative,44.78 ± 55.22,13.3 ± 18.71,11.24 ± 70.21,2.9 ± 22.77
pale2021,105.45 ± 113.31,29.41 ± 29.32,71.9 ± 137.08,18.9 ± 36.98

### Compute mean performance of all models evaluated per data imputation strategy

In [84]:
#datasets = ['RR-Interval', 'RR-Interval-Median-Imputed', 'RR-Interval-Include-Nan', 'Without-RR-Interval', 'Without-RR-Interval-Median-Imputed', 'Without-RR-Interval-Include-Nan']
datasets = ['RR-Interval-Include-Nan', 'RR-Interval-Median-Imputed']
dataset_results = pd.DataFrame()
for dataset in datasets:
    dataset_results[dataset] = summarized_error_metrics[summarized_error_metrics.index.str.endswith(f'_{dataset}')].mean(axis=0)
dataset_results = dataset_results.T
dataset_results

                                mean                                      std  \
metric_type                      MAE      MARE        ME       MRE        MAE
RR-Interval-Include-Nan     9.135756  2.749951 -0.030876 -0.227156  13.094406
RR-Interval-Median-Imputed  8.925654  2.700109 -0.045767 -0.220022  14.030059


metric_type                     MARE         ME       MRE
RR-Interval-Include-Nan     4.230232  15.969036  5.041271
RR-Interval-Median-Imputed  4.456960  16.641267  5.210380

In [85]:
create_ml_algo_performance_table(dataset_results)

                                   MAE       MARE           ME         MRE
RR-Interval-Median-Imputed  8.9 ± 14.0  2.7 ± 4.5  -0.0 ± 16.6  -0.2 ± 5.2
RR-Interval-Include-Nan     9.1 ± 13.1  2.7 ± 4.2  -0.0 ± 16.0  -0.2 ± 5.0

### Compute error metrics per datasource (Empkins, Guardian)

#### EmpkinS

In [61]:
empkins_data = merged_ml_results_metrics[merged_ml_results_metrics.index.get_level_values('condition') != 'Dummy'].droplevel('condition')
guardian_data = merged_ml_results_metrics.xs(key='Dummy', level='condition')

In [62]:
summary_metrics_empkins = describe_ml_results_df(empkins_data)
metric_export_paper_empkins = create_ml_algo_performance_table(summary_metrics_empkins, n_algos=15)
metric_export_paper_empkins

,MAE,MARE,ME,MRE
B-Point Algorithm,,,,
SS_SFM_SVR_RR-Interval,7.7 ± 11.9,2.9 ± 4.7,-1.1 ± 14.1,-0.6 ± 5.5
MinMax_KBest_RFR_RR-Interval,7.7 ± 11.0,2.8 ± 4.1,0.3 ± 13.5,-0.1 ± 5.0
SS_SFM_RFR_RR-Interval,7.8 ± 10.8,2.8 ± 4.0,0.4 ± 13.3,-0.1 ± 4.9
SS_KBest_RFR_RR-Interval,7.8 ± 11.1,2.8 ± 4.2,0.4 ± 13.6,-0.1 ± 5.0
MinMax_SFM_RFR_RR-Interval,7.8 ± 10.9,2.8 ± 4.1,0.3 ± 13.4,-0.1 ± 5.0
SS_SFM_SVR_Without-RR-Interval,7.9 ± 12.3,2.9 ± 4.9,-0.9 ± 14.6,-0.6 ± 5.6
SS_KBest_RFR_Without-RR-Interval,7.9 ± 11.2,2.9 ± 4.1,0.4 ± 13.7,-0.1 ± 5.0
MinMax_KBest_RFR_Without-RR-Interval,7.9 ± 11.2,2.9 ± 4.1,0.5 ± 13.7,-0.1 ± 5.0
SS_SFM_RFR_Without-RR-Interval,8.0 ± 11.1,2.9 ± 4.1,0.5 ± 13.7,-0.1 ± 5.0
SS_KBest_SVR_RR-Interval,8.0 ± 13.7,2.9 ± 5.1,0.3 ± 15.8,-0.2 ± 5.9
MinMax_SFM_RFR_Without-RR-Interval,8.1 ± 11.2,2.9 ± 4.2,0.5 ± 13.8,-0.0 ± 5.1
SS_KBest_SVR_Without-RR-Interval,8.1 ± 13.8,3.0 ± 5.2,0.3 ± 16.0,-0.2 ± 6.0
MinMax_SFM_DTR_Without-RR-Interval,8.3 ± 13.3,3.0 ± 4.9,0.4 ± 15.7,-0.1 ± 5.7
MinMax_None_RFR_RR-Interval-Include-Nan,8.3 ± 11.5,3.1 ± 4.6,-0.1 ± 14.2,-0.3 ± 5.5
SS_SFM_KNR_Without-RR-Interval,8.3 ± 10.9,3.0 ± 4.1,0.1 ± 13.7,-0.2 ± 5.1

#### Guardian

In [63]:
summary_metrics_guardian = describe_ml_results_df(guardian_data)
metric_export_paper_guardian = create_ml_algo_performance_table(summary_metrics_guardian, n_algos=15)
metric_export_paper_guardian

,MAE,MARE,ME,MRE
B-Point Algorithm,,,,
SS_KBest_SVR_RR-Interval,7.6 ± 13.4,1.8 ± 3.4,-0.9 ± 15.4,-0.4 ± 3.9
SS_KBest_SVR_Without-RR-Interval,7.6 ± 13.3,1.8 ± 3.4,-0.9 ± 15.3,-0.4 ± 3.9
MinMax_KBest_RFR_Without-RR-Interval,7.7 ± 12.1,1.9 ± 3.2,-0.3 ± 14.3,-0.2 ± 3.7
MinMax_SFM_RFR_RR-Interval,7.8 ± 12.0,1.9 ± 3.1,0.0 ± 14.3,-0.1 ± 3.6
MinMax_KBest_RFR_RR-Interval,7.8 ± 11.9,1.9 ± 3.1,-0.1 ± 14.2,-0.2 ± 3.6
SS_KBest_RFR_Without-RR-Interval,7.8 ± 11.8,1.9 ± 3.1,-0.4 ± 14.2,-0.2 ± 3.6
SS_SFM_RFR_RR-Interval,7.8 ± 11.8,1.9 ± 3.1,-0.1 ± 14.2,-0.2 ± 3.6
SS_SFM_SVR_Without-RR-Interval,7.8 ± 13.0,1.9 ± 3.4,-0.7 ± 15.2,-0.3 ± 3.8
SS_SFM_RFR_Without-RR-Interval,7.8 ± 12.0,1.9 ± 3.2,-0.2 ± 14.3,-0.2 ± 3.7
SS_KBest_RFR_RR-Interval,7.8 ± 12.0,1.9 ± 3.1,-0.1 ± 14.4,-0.2 ± 3.7
MinMax_SFM_RFR_Without-RR-Interval,7.9 ± 12.1,1.9 ± 3.2,-0.2 ± 14.4,-0.2 ± 3.7
MinMax_None_RFR_RR-Interval-Include-Nan,8.0 ± 12.6,1.9 ± 3.2,0.0 ± 14.9,-0.1 ± 3.7
SS_SFM_DTR_Without-RR-Interval,8.0 ± 14.2,1.9 ± 3.7,-0.6 ± 16.3,-0.3 ± 4.1
SS_KBest_DTR_RR-Interval,8.0 ± 14.6,1.9 ± 3.7,-0.3 ± 16.6,-0.2 ± 4.2
MinMax_None_RFR_Without-RR-Interval-Include-Nan,8.0 ± 13.4,1.9 ± 3.4,0.0 ± 15.6,-0.1 ± 3.9