## Dataframe conversion from wide to long format

### Setup and Helper Functions

#### Imports

In [1]:
from pathlib import Path

import pandas as pd

#### Datapaths

In [2]:
data_path = Path("../../results")

### Convert merged results from wide to long

In [3]:
merged_ml_results = pd.read_csv(
    data_path.joinpath("merged_ml_results_b_point_paper_rr_only.csv"), index_col=[0, 1, 2, 3]
)
merged_ml_results

                                                            b_point_sample_reference  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          388.0
                                    1                                          404.0
                                    3                                          376.0
                                    4                                          390.0
                                    5                                          386.0
...                                                                              ...
VP_032      tsst      Talk          39                                         310.0
                                    40                                         322.0
                                    41                                         340.0
                                    42                                         311.0
                                    43                                         307.0

                                                            arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 438.0
                                    1                                                 340.0
                                    3                                                 382.0
                                    4                                                 394.0
                                    5                                                 398.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                335.0
                                    40                                                331.0
                                    41                                                317.0
                                    42                                                365.0
                                    43                                                342.0

                                                            arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                             398.0
                                    1                                             350.0
                                    3                                             296.0
                                    4                                             344.0
                                    5                                             312.0
...                                                                                 ...
VP_032      tsst      Talk          39                                            276.0
                                    40                                            298.0
                                    41                                            300.0
                                    42                                            324.0
                                    43                                            313.0

                                                            arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                            394.0
                                    1                                            244.0
                                    3                                            386.0
                                    4                                            396.0
                                    5                                            388.0
...                                                                                ...
VP_032      tsst      Talk          39                                           324.0
                                    40                                           330.0
                                    41                                           348.0
                                    42                                           366.0
                                    43                                           356.0

                                                            debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              452.0
                                    1                                              388.0
                                    3                                              366.0
                                    4                                              376.0
                                    5                                              418.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             300.0
                                    40                                             311.0
                                    41                                             330.0
                                    42                                             347.0
                                    43                                             285.0

                                                            drost2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           400.0
                                    1                           420.0
                                    3                           386.0
                                    4                           396.0
                                    5                           392.0
...                                                               ...
VP_032      tsst      Talk          39                          318.0
                                    40                          322.0
                                    41                          343.0
                                    42                          354.0
                                    43                          332.0

                                                            forouzanfar2018  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                 550.0
                                    1                                 402.0
                                    3                                 388.0
                                    4                                 398.0
                                    5                                 390.0
...                                                                     ...
VP_032      tsst      Talk          39                                306.0
                                    40                                311.0
                                    41                                309.0
                                    42                                305.0
                                    43                                302.0

                                                            lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              412.0
                                    1                                              404.0
                                    3                                              366.0
                                    4                                              372.0
                                    5                                              378.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             305.0
                                    40                                             321.0
                                    41                                             332.0
                                    42                                             351.0
                                    43                                             341.0

                                                            lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 384.0
                                    1                                                 384.0
                                    3                                                 348.0
                                    4                                                 348.0
                                    5                                                 354.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                294.0
                                    40                                                303.0
                                    41                                                322.0
                                    42                                                337.0
                                    43                                                329.0

                                                            miljkovic2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                               442.0
                                    1                               288.0
                                    3                               386.0
                                    4                               398.0
                                    5                               392.0
...                                                                   ...
VP_032      tsst      Talk          39                              308.0
                                    40                              329.0
                                    41                              292.0
                                    42                              312.0
                                    43                              334.0

                                                            ...  \
participant condition phase         heartbeat_id_reference  ...
GDN0005     Dummy     HoldingBreath 0                       ...
                                    1                       ...
                                    3                       ...
                                    4                       ...
                                    5                       ...
...                                                         ...
VP_032      tsst      Talk          39                      ...
                                    40                      ...
                                    41                      ...
                                    42                      ...
                                    43                      ...

                                                            SS_KBest_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    412.398584
                                    1                                                    403.408903
                                    3                                                    376.768489
                                    4                                                    388.625256
                                    5                                                    385.761830
...                                                                                             ...
VP_032      tsst      Talk          39                                                   309.424969
                                    40                                                   312.280534
                                    41                                                   331.079043
                                    42                                                   342.187956
                                    43                                                   307.324979

                                                            SS_KBest_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    421.288455
                                    1                                                    401.485786
                                    3                                                    376.403625
                                    4                                                    388.643213
                                    5                                                    386.743597
...                                                                                             ...
VP_032      tsst      Talk          39                                                   319.918637
                                    40                                                   317.460122
                                    41                                                   329.227094
                                    42                                                   339.654610
                                    43                                                   314.443751

                                                            MinMax_SFM_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                           392.0
                                    1                                                           406.0
                                    3                                                           376.0
                                    4                                                           388.0
                                    5                                                           384.0
...                                                                                               ...
VP_032      tsst      Talk          39                                                          311.0
                                    40                                                          321.0
                                    41                                                          334.0
                                    42                                                          351.5
                                    43                                                          307.5

                                                            MinMax_SFM_RFR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      430.592322
                                    1                                                      404.075637
                                    3                                                      375.332204
                                    4                                                      389.011683
                                    5                                                      385.868359
...                                                                                               ...
VP_032      tsst      Talk          39                                                     310.134872
                                    40                                                     317.331053
                                    41                                                     330.211990
                                    42                                                     335.669733
                                    43                                                     310.617416

                                                            MinMax_SFM_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      415.841272
                                    1                                                      405.752970
                                    3                                                      377.956802
                                    4                                                      388.530034
                                    5                                                      386.934831
...                                                                                               ...
VP_032      tsst      Talk          39                                                     308.018902
                                    40                                                     310.554869
                                    41                                                     330.103150
                                    42                                                     339.014104
                                    43                                                     313.036780

                                                            MinMax_SFM_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      416.688480
                                    1                                                      396.160236
                                    3                                                      377.268411
                                    4                                                      387.233813
                                    5                                                      390.040129
...                                                                                               ...
VP_032      tsst      Talk          39                                                     310.277235
                                    40                                                     315.145165
                                    41                                                     329.741920
                                    42                                                     342.487887
                                    43                                                     306.995532

                                                            MinMax_KBest_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                             403.0
                                    1                                                             404.0
                                    3                                                             376.0
                                    4                                                             388.0
                                    5                                                             386.0

In [4]:
merged_ml_results_long = merged_ml_results.reset_index().melt(
    id_vars=["participant", "condition", "phase", "heartbeat_id_reference"], var_name="Algorithm", value_name="B-Point"
)
merged_ml_results_long

,participant,condition,phase,heartbeat_id_reference,Algorithm,B-Point
0,GDN0005,Dummy,HoldingBreath,0,b_point_sample_reference,388.000000
1,GDN0005,Dummy,HoldingBreath,1,b_point_sample_reference,404.000000
2,GDN0005,Dummy,HoldingBreath,3,b_point_sample_reference,376.000000
3,GDN0005,Dummy,HoldingBreath,4,b_point_sample_reference,390.000000
4,GDN0005,Dummy,HoldingBreath,5,b_point_sample_reference,386.000000
...,...,...,...,...,...,...
427077,VP_032,tsst,Talk,39,MinMax_KBest_KNR_RR-Interval-Median-Imputed,319.951963
427078,VP_032,tsst,Talk,40,MinMax_KBest_KNR_RR-Interval-Median-Imputed,317.834377
427079,VP_032,tsst,Talk,41,MinMax_KBest_KNR_RR-Interval-Median-Imputed,329.172779
427080,VP_032,tsst,Talk,42,MinMax_KBest_KNR_RR-Interval-Median-Imputed,339.668703
427081,VP_032,tsst,Talk,43,MinMax_KBest_KNR_RR-Interval-Median-Imputed,314.430533

In [ ]:
# merged_ml_results_long.to_csv(data_path.joinpath("merged_ml_results_b_point_paper_long_rr_only.csv"), index=False)

### Convert merged error metrics dataframe from wide to long

In [6]:
merged_ml_results_error_metrics = pd.read_csv(
    data_path.joinpath("merged_ml_results_b_point_error_metrics_rr_only.csv"), index_col=[0, 1, 2, 3]
)
merged_ml_results_error_metrics

                                                            arbol2017-isoelectric-crossings_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                       -50.0
                                    1                                                        64.0
                                    3                                                        -6.0
                                    4                                                        -4.0
                                    5                                                       -12.0
...                                                                                           ...
VP_032      tsst      Talk          39                                                      -25.0
                                    40                                                       -9.0
                                    41                                                       23.0
                                    42                                                      -54.0
                                    43                                                      -35.0

                                                            arbol2017-isoelectric-crossings_rel_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                       -0.128866
                                    1                                                        0.158416
                                    3                                                       -0.015957
                                    4                                                       -0.010256
                                    5                                                       -0.031088
...                                                                                               ...
VP_032      tsst      Talk          39                                                      -0.080645
                                    40                                                      -0.027950
                                    41                                                       0.067647
                                    42                                                      -0.173633
                                    43                                                      -0.114007

                                                            arbol2017-isoelectric-crossings_abs_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                            50.0
                                    1                                                            64.0
                                    3                                                             6.0
                                    4                                                             4.0
                                    5                                                            12.0
...                                                                                               ...
VP_032      tsst      Talk          39                                                           25.0
                                    40                                                            9.0
                                    41                                                           23.0
                                    42                                                           54.0
                                    43                                                           35.0

                                                            arbol2017-isoelectric-crossings_abs_rel_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                            0.128866
                                    1                                                            0.158416
                                    3                                                            0.015957
                                    4                                                            0.010256
                                    5                                                            0.031088
...                                                                                                   ...
VP_032      tsst      Talk          39                                                           0.080645
                                    40                                                           0.027950
                                    41                                                           0.067647
                                    42                                                           0.173633
                                    43                                                           0.114007

                                                            arbol2017-second-derivative_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                   -10.0
                                    1                                                    54.0
                                    3                                                    80.0
                                    4                                                    46.0
                                    5                                                    74.0
...                                                                                       ...
VP_032      tsst      Talk          39                                                   34.0
                                    40                                                   24.0
                                    41                                                   40.0
                                    42                                                  -13.0
                                    43                                                   -6.0

                                                            arbol2017-second-derivative_rel_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                   -0.025773
                                    1                                                    0.133663
                                    3                                                    0.212766
                                    4                                                    0.117949
                                    5                                                    0.191710
...                                                                                           ...
VP_032      tsst      Talk          39                                                   0.109677
                                    40                                                   0.074534
                                    41                                                   0.117647
                                    42                                                  -0.041801
                                    43                                                  -0.019544

                                                            arbol2017-second-derivative_abs_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                        10.0
                                    1                                                        54.0
                                    3                                                        80.0
                                    4                                                        46.0
                                    5                                                        74.0
...                                                                                           ...
VP_032      tsst      Talk          39                                                       34.0
                                    40                                                       24.0
                                    41                                                       40.0
                                    42                                                       13.0
                                    43                                                        6.0

                                                            arbol2017-second-derivative_abs_rel_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                        0.025773
                                    1                                                        0.133663
                                    3                                                        0.212766
                                    4                                                        0.117949
                                    5                                                        0.191710
...                                                                                               ...
VP_032      tsst      Talk          39                                                       0.109677
                                    40                                                       0.074534
                                    41                                                       0.117647
                                    42                                                       0.041801
                                    43                                                       0.019544

                                                            arbol2017-third-derivative_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                   -6.0
                                    1                                                  160.0
                                    3                                                  -10.0
                                    4                                                   -6.0
                                    5                                                   -2.0
...                                                                                      ...
VP_032      tsst      Talk          39                                                 -14.0
                                    40                                                  -8.0
                                    41                                                  -8.0
                                    42                                                 -55.0
                                    43                                                 -49.0

                                                            arbol2017-third-derivative_rel_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                  -0.015464
                                    1                                                   0.396040
                                    3                                                  -0.026596
                                    4                                                  -0.015385
                                    5                                                  -0.005181
...                                                                                          ...
VP_032      tsst      Talk          39                                                 -0.045161
                                    40                                                 -0.024845
                                    41                                                 -0.023529
                                    42                                                 -0.176849
                                    43                                                 -0.159609

                                                            ...  \
participant condition phase         heartbeat_id_reference  ...
GDN0005     Dummy     HoldingBreath 0                       ...
                                    1                       ...
                                    3                       ...
                                    4                       ...
                                    5                       ...
...                                                         ...
VP_032      tsst      Talk          39                      ...
                                    40                      ...
                                    41                      ...
                                    42                      ...
                                    43                      ...

                                                            MinMax_KBest_RFR_RR-Interval-Median-Imputed_abs_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                               38.637331
                                    1                                                                0.534634
                                    3                                                                1.208438
                                    4                                                                0.566338
                                    5                                                                0.062038
...                                                                                                       ...
VP_032      tsst      Talk          39                                                               0.595307
                                    40                                                               6.118376
                                    41                                                              14.372025
                                    42                                                              22.193183
                                    43                                                               1.492748

                                                            MinMax_KBest_RFR_RR-Interval-Median-Imputed_abs_rel_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                                0.099581
                                    1                                                                0.001323
                                    3                                                                0.003214
                                    4                                                                0.001452
                                    5                                                                0.000161
...                                                                                                       ...
VP_032      tsst      Talk          39                                                               0.001920
                                    40                                                               0.019001
                                    41                                                               0.042271
                                    42                                                               0.071361
                                    43                                                               0.004862

                                                            MinMax_KBest_SVR_RR-Interval-Median-Imputed_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                              -29.722668
                                    1                                                               -3.185039
                                    3                                                               -3.388331
                                    4                                                                1.192601
                                    5                                                               -2.201816
...                                                                                                       ...
VP_032      tsst      Talk          39                                                               1.646730
                                    40                                                              10.992391
                                    41                                                              10.085479
                                    42                                                             -28.168398
                                    43                                                              -6.518547

                                                            MinMax_KBest_SVR_RR-Interval-Median-Imputed_rel_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                               -0.076605
                                    1                                                               -0.007884
                                    3                                                               -0.009012
                                    4                                                                0.003058
                                    5                                                               -0.005704
...                                                                                                       ...
VP_032      tsst      Talk          39                                                               0.005312
                                    40                                                               0.034138
                                    41                                                               0.029663
                                    42                                                              -0.090574
                                    43                                                              -0.021233

                                                            MinMax_KBest_SVR_RR-Interval-Median-Imputed_abs_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                               29.722668
                                    1                                                                3.185039
                                    3                                                                3.388331
                                    4                                                                1.192601
                                    5                                                                2.201816
...                                                                                                       ...
VP_032      tsst      Talk          39                                                               1.646730
                                    40                                                              10.992391

In [7]:
merged_ml_results_error_metrics_long = merged_ml_results_error_metrics.reset_index().melt(
    id_vars=["participant", "condition", "phase", "heartbeat_id_reference"], var_name="Algorithm", value_name="Error"
)
merged_ml_results_error_metrics_long

,participant,condition,phase,heartbeat_id_reference,Algorithm,Error
0,GDN0005,Dummy,HoldingBreath,0,arbol2017-isoelectric-crossings_error,-50.000000
1,GDN0005,Dummy,HoldingBreath,1,arbol2017-isoelectric-crossings_error,64.000000
2,GDN0005,Dummy,HoldingBreath,3,arbol2017-isoelectric-crossings_error,-6.000000
3,GDN0005,Dummy,HoldingBreath,4,arbol2017-isoelectric-crossings_error,-4.000000
4,GDN0005,Dummy,HoldingBreath,5,arbol2017-isoelectric-crossings_error,-12.000000
...,...,...,...,...,...,...
1618411,VP_032,tsst,Talk,39,MinMax_KBest_KNR_RR-Interval-Median-Imputed_ab...,0.032103
1618412,VP_032,tsst,Talk,40,MinMax_KBest_KNR_RR-Interval-Median-Imputed_ab...,0.012937
1618413,VP_032,tsst,Talk,41,MinMax_KBest_KNR_RR-Interval-Median-Imputed_ab...,0.031845
1618414,VP_032,tsst,Talk,42,MinMax_KBest_KNR_RR-Interval-Median-Imputed_ab...,0.092182
1618415,VP_032,tsst,Talk,43,MinMax_KBest_KNR_RR-Interval-Median-Imputed_ab...,0.024204

In [ ]:
# merged_ml_results_error_metrics_long.to_csv(
#     data_path.joinpath("merged_ml_results_b_point_error_metrics_long_rr_only.csv"), index=False
# )